#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mobilizon"
name = "Mobilizon"
description.en = "Decentralized and federated platform to organize events"
description.fr = "Plateforme décentralisée et fédérée pour organiser des événements"

version = "4.0.0~ynh2"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://joinmobilizon.org/"
demo = "https://demo.mobilizon.org"
userdoc = "https://docs.joinmobilizon.org"
code = "https://framagit.org/framasoft/mobilizon/"
fund = "https://soutenir.framasoft.org/"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64"]
multi_instance = false
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    amd64.url = "https://packages.joinmobilizon.org/4.0.0/mobilizon_4.0.0_amd64-debian-bullseye.tar.gz"
    amd64.sha256 = "a0007f7564c01ea8b0bfc9b3b32742473839b0217aae59dea74eacfd3b1774ac"
    arm64.url = "https://packages.joinmobilizon.org/4.0.0/mobilizon_4.0.0_arm64-debian-bullseye.tar.gz"
    arm64.sha256 = "c63495d8a176e28843d0217c2b273bb5aca84123658286101a962467fc6f045b"

    autoupdate.strategy = "latest_gitlab_release"
    autoupdate.asset.amd64 = "mobilizon_.*_amd64-debian-bullseye.tar.gz"
    autoupdate.asset.arm64 = "mobilizon_.*_arm64-debian-bullseye.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["uploads"]
    owner = "__APP__:rwx"
    group = "__APP__:rwx"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = [
        "postgresql",
        "postgresql-client",
        "postgresql-contrib",
        "postgis",
        "postgresql-postgis-scripts",
        "postgresql-postgis",
        "argon2",
        "imagemagick",
        "webp",
        "gifsicle",
        "jpegoptim",
        "optipng",
        "pngquant",
        "file",
    ]

    [resources.database]
    type = "postgresql"
